import { app, BrowserWindow, dialog, ipcMain, Menu, protocol, safeStorage, shell } from "electron";
import path from "node:path";
import fs from "node:fs";
import crypto from "node:crypto";
import Database from "better-sqlite3";
import { PublicClientApplication, type ICachePlugin } from "@azure/msal-node";
import { z } from "zod";

const SCOPES = ["User.Read", "Files.Read", "Mail.Send", "offline_access"];
let mainWindow: BrowserWindow | null = null;
let db: Database.Database;
let msal: PublicClientApplication | null = null;
let authInProgress = false;
let microsoftClientId = "";

type Centro = { id?: number; parqueCentro: string; localidad: string; emailPrimario: string; emailSecundario?: string; oneDriveFolderPath?: string; activo: boolean };
type Template = { id?: number; nombre: string; asuntoTemplate: string; cuerpoTemplate: string; saludoDefault?: string; activo: boolean };
const dataDir = () => path.join(app.getPath("userData"), "data");
const dbPath = () => path.join(dataDir(), "envio-cifras.sqlite");
const attachmentsDir = () => path.join(dataDir(), "adjuntos");
const cachePath = () => path.join(dataDir(), "msal-cache.bin");
const now = () => new Date().toISOString();
const monthName = (month: string) => new Intl.DateTimeFormat("es-ES", { month: "long" }).format(new Date(2026, Number(month) - 1, 1));
const normalizePath = (value?: string | null) => (value || "").trim().replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
const expectedFile = (year: number, month: string, extension: string) => `DECLARACION_VENTAS_${year}.${month}.${extension.replace(/^\./, "")}`;

function openDatabase() {
  fs.mkdirSync(dataDir(), { recursive: true }); fs.mkdirSync(attachmentsDir(), { recursive: true });
  db = new Database(dbPath()); db.pragma("journal_mode = WAL"); db.pragma("foreign_keys = ON");
  db.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS centros (id INTEGER PRIMARY KEY, parque_centro TEXT NOT NULL, localidad TEXT NOT NULL, email_primario TEXT NOT NULL, email_secundario TEXT, onedrive_folder_path TEXT, activo INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS templates (id INTEGER PRIMARY KEY, nombre TEXT NOT NULL, asunto_template TEXT NOT NULL, cuerpo_template TEXT NOT NULL, saludo_default TEXT, activo INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS lotes (id INTEGER PRIMARY KEY, anio INTEGER NOT NULL, mes_numero TEXT NOT NULL, mes_nombre TEXT NOT NULL, extension_archivo TEXT NOT NULL, template_id INTEGER NOT NULL, estado TEXT NOT NULL DEFAULT 'borrador', sent_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(anio, mes_numero, extension_archivo));
    CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY, lote_id INTEGER NOT NULL, centro_id INTEGER, parque_centro_snapshot TEXT NOT NULL, localidad_snapshot TEXT NOT NULL, destinatarios_json TEXT NOT NULL, asunto TEXT NOT NULL, cuerpo TEXT NOT NULL, archivo_nombre TEXT NOT NULL, onedrive_path_esperado TEXT, storage_path TEXT, storage_original_file_name TEXT, archivo_origen TEXT NOT NULL DEFAULT 'ninguno', archivo_estado TEXT NOT NULL DEFAULT 'pendiente', envio_estado TEXT NOT NULL DEFAULT 'pendiente', error TEXT, sent_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);`);
}
function setting(key: string) { return (db.prepare("SELECT value FROM settings WHERE key=?").get(key) as { value?: string } | undefined)?.value || null; }
function setSetting(key: string, value: string) { db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(key, value); }
function redirectUri() { return `msal${microsoftClientId}://auth`; }
function protocolName() { return `msal${microsoftClientId}`; }
function crypt(value: string) { if (!safeStorage.isEncryptionAvailable()) throw new Error("El cifrado seguro de Windows no está disponible."); return safeStorage.encryptString(value); }
function decrypt(value: Buffer) { return safeStorage.decryptString(value); }
function configureMsal() {
  microsoftClientId = setting("microsoft_client_id") || "";
  if (!microsoftClientId) { msal = null; return; }
  const cachePlugin: ICachePlugin = { beforeCacheAccess: async (ctx) => { if (fs.existsSync(cachePath())) ctx.tokenCache.deserialize(decrypt(fs.readFileSync(cachePath()))); }, afterCacheAccess: async (ctx) => { if (ctx.cacheHasChanged) fs.writeFileSync(cachePath(), crypt(ctx.tokenCache.serialize())); } };
  msal = new PublicClientApplication({ auth: { clientId: microsoftClientId, authority: "https://login.microsoftonline.com/common" }, cache: { cachePlugin } });
}
function registerMicrosoftProtocol() { if (microsoftClientId) app.setAsDefaultProtocolClient(protocolName()); }
async function graph(pathName: string, init: RequestInit = {}) {
  if (!msal) throw new Error("Microsoft no está inicializado."); const accounts = await msal.getTokenCache().getAllAccounts(); const account = accounts[0]; if (!account) throw new Error("Conecta una cuenta Microsoft antes de continuar.");
  const token = await msal.acquireTokenSilent({ account, scopes: SCOPES });
  const response = await fetch(`https://graph.microsoft.com/v1.0${pathName}`, { ...init, headers: { authorization: `Bearer ${token.accessToken}`, ...(init.headers || {}) } });
  if (!response.ok) { const data = await response.json().catch(() => ({})) as { error?: { message?: string } }; throw new Error(data.error?.message || "Microsoft Graph no pudo completar la operación."); }
  return response;
}
async function microsoftStatus() { if (!msal) return { configured: false, connected: false, accountEmail: null, displayName: null, rootPath: setting("onedrive_root") }; const account = (await msal.getTokenCache().getAllAccounts())[0]; return { configured: true, clientId: microsoftClientId, connected: !!account, accountEmail: account?.username || null, displayName: account?.name || null, rootPath: setting("onedrive_root") }; }
function render(template: string, values: Record<string, string>) { return template.replace(/\{\{\s*([a-z_]+)\s*\}\}/gi, (_, key) => values[key] ?? ""); }
function mapCentro(row: any): Centro { return { id: row.id, parqueCentro: row.parque_centro, localidad: row.localidad, emailPrimario: row.email_primario, emailSecundario: row.email_secundario || "", oneDriveFolderPath: row.onedrive_folder_path || "", activo: !!row.activo }; }
function mapTemplate(row: any): Template { return { id: row.id, nombre: row.nombre, asuntoTemplate: row.asunto_template, cuerpoTemplate: row.cuerpo_template, saludoDefault: row.saludo_default || "", activo: !!row.activo }; }
function mapLote(row: any) { return { id: row.id, anio: row.anio, mesNumero: row.mes_numero, mesNombre: row.mes_nombre, extensionArchivo: row.extension_archivo, estado: row.estado, sentAt: row.sent_at }; }
function mapItem(row: any) { return { id: row.id, parqueCentroSnapshot: row.parque_centro_snapshot, localidadSnapshot: row.localidad_snapshot, destinatarios: JSON.parse(row.destinatarios_json), asunto: row.asunto, cuerpo: row.cuerpo, archivoNombre: row.archivo_nombre, oneDrivePathEsperado: row.onedrive_path_esperado, storageOriginalFileName: row.storage_original_file_name, archivoEstado: row.archivo_estado, envioEstado: row.envio_estado, error: row.error }; }
async function sendOutlookMail(row: any, bytes: Buffer) {
  const filename = row.storage_original_file_name || row.archivo_nombre;
  const message = { subject: row.asunto, body: { contentType: "Text", content: row.cuerpo }, toRecipients: JSON.parse(row.destinatarios_json).map((address: string) => ({ emailAddress: { address } })) };
  if (bytes.byteLength <= 3 * 1024 * 1024) {
    await graph("/me/sendMail", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ message: { ...message, attachments: [{ "@odata.type": "#microsoft.graph.fileAttachment", name: filename, contentBytes: bytes.toString("base64") }] }, saveToSentItems: true }) });
    return;
  }
  const draft = await graph("/me/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(message) });
  const draftData = await draft.json() as { id?: string };
  if (!draftData.id) throw new Error("Outlook no pudo crear el borrador para el adjunto.");
  const session = await graph(`/me/messages/${draftData.id}/attachments/createUploadSession`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ AttachmentItem: { attachmentType: "file", name: filename, size: bytes.byteLength } }) });
  const sessionData = await session.json() as { uploadUrl?: string };
  if (!sessionData.uploadUrl) throw new Error("Outlook no pudo crear la sesión de carga del adjunto.");
  const uploaded = await fetch(sessionData.uploadUrl, { method: "PUT", headers: { "Content-Length": String(bytes.byteLength), "Content-Range": `bytes 0-${bytes.byteLength - 1}/${bytes.byteLength}` }, body: bytes as unknown as BodyInit });
  if (!uploaded.ok) throw new Error("No se pudo subir el adjunto a Outlook.");
  await graph(`/me/messages/${draftData.id}/send`, { method: "POST" });
}
function registerHandlers() {
  ipcMain.handle("centros:list", () => db.prepare("SELECT * FROM centros ORDER BY parque_centro").all().map(mapCentro));
  ipcMain.handle("centros:save-all", (_e, values: unknown) => { const rows = z.array(z.object({ id: z.number().optional(), parqueCentro: z.string().trim().min(2), localidad: z.string().trim().min(2), emailPrimario: z.string().trim().email(), emailSecundario: z.string().trim().email().or(z.literal("")).optional(), oneDriveFolderPath: z.string().max(1000).optional(), activo: z.boolean() })).parse(values); const save = db.transaction(() => { for (const row of rows) { const data = [row.parqueCentro, row.localidad, row.emailPrimario, row.emailSecundario || null, normalizePath(row.oneDriveFolderPath) || null, row.activo ? 1 : 0, now()]; if (row.id) db.prepare("UPDATE centros SET parque_centro=?,localidad=?,email_primario=?,email_secundario=?,onedrive_folder_path=?,activo=?,updated_at=? WHERE id=?").run(...data, row.id); else db.prepare("INSERT INTO centros(parque_centro,localidad,email_primario,email_secundario,onedrive_folder_path,activo,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)").run(...data, now()); } }); save(); return true; });
  ipcMain.handle("templates:list", () => db.prepare("SELECT * FROM templates ORDER BY nombre").all().map(mapTemplate));
  ipcMain.handle("templates:save-all", (_e, values: unknown) => { const rows = z.array(z.object({ id: z.number().optional(), nombre: z.string().trim().min(2), asuntoTemplate: z.string().trim().min(2), cuerpoTemplate: z.string().trim().min(2), saludoDefault: z.string().optional(), activo: z.boolean() })).parse(values); const save = db.transaction(() => { for (const row of rows) { const data = [row.nombre,row.asuntoTemplate,row.cuerpoTemplate,row.saludoDefault || null,row.activo ? 1 : 0,now()]; if (row.id) db.prepare("UPDATE templates SET nombre=?,asunto_template=?,cuerpo_template=?,saludo_default=?,activo=?,updated_at=? WHERE id=?").run(...data,row.id); else db.prepare("INSERT INTO templates(nombre,asunto_template,cuerpo_template,saludo_default,activo,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(...data,now()); } }); save(); return true; });
  ipcMain.handle("lotes:list", () => db.prepare("SELECT * FROM lotes ORDER BY anio DESC, mes_numero DESC, created_at DESC").all().map(mapLote));
  ipcMain.handle("lotes:get", (_e, id: number) => { const lote = db.prepare("SELECT * FROM lotes WHERE id=?").get(id); if (!lote) throw new Error("Lote no encontrado."); return { ...mapLote(lote), items: db.prepare("SELECT * FROM items WHERE lote_id=? ORDER BY parque_centro_snapshot").all(id).map(mapItem) }; });
  ipcMain.handle("lotes:create", (_e, payload: unknown) => { const value = z.object({ anio: z.number().int().min(2000).max(2100), mesNumero: z.string().regex(/^0[1-9]$|^1[0-2]$/), extensionArchivo: z.string().trim().min(1).max(20), templateId: z.number().int().positive() }).parse(payload); const existing = db.prepare("SELECT * FROM lotes WHERE anio=? AND mes_numero=? AND extension_archivo=?").get(value.anio,value.mesNumero,value.extensionArchivo.replace(/^\./,"")); if (existing) return mapLote(existing); const template: any = db.prepare("SELECT * FROM templates WHERE id=? AND activo=1").get(value.templateId); if (!template) throw new Error("Selecciona una plantilla activa."); const inserted = db.prepare("INSERT INTO lotes(anio,mes_numero,mes_nombre,extension_archivo,template_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").run(value.anio,value.mesNumero,monthName(value.mesNumero),value.extensionArchivo.replace(/^\./,""),value.templateId,now(),now()); const centers: any[] = db.prepare("SELECT * FROM centros WHERE activo=1 ORDER BY parque_centro").all(); const add = db.prepare("INSERT INTO items(lote_id,centro_id,parque_centro_snapshot,localidad_snapshot,destinatarios_json,asunto,cuerpo,archivo_nombre,onedrive_path_esperado,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)"); for (const c of centers) { const file = expectedFile(value.anio,value.mesNumero,value.extensionArchivo); const ctx = { saludo: template.saludo_default || "Buenos días", parque_centro: c.parque_centro, localidad: c.localidad, mes_nombre: monthName(value.mesNumero), ano: String(value.anio), año: String(value.anio), archivo_nombre: file }; add.run(inserted.lastInsertRowid,c.id,c.parque_centro,c.localidad,JSON.stringify([c.email_primario,c.email_secundario].filter(Boolean)),render(template.asunto_template,ctx),render(template.cuerpo_template,ctx),file,`${normalizePath(c.onedrive_folder_path)}/${file}`,now(),now()); } return mapLote(db.prepare("SELECT * FROM lotes WHERE id=?").get(inserted.lastInsertRowid)); });
  ipcMain.handle("lotes:search", async (_e, loteId: number) => { const root = normalizePath(setting("onedrive_root")); if (!root) throw new Error("Define la carpeta raíz de OneDrive antes de buscar."); const rows: any[] = db.prepare("SELECT * FROM items WHERE lote_id=?").all(loteId); for (const row of rows) { try { const full = `/${root}/${normalizePath(row.onedrive_path_esperado)}`; await graph(`/me/drive/root:${encodeURI(full)}:`); db.prepare("UPDATE items SET archivo_estado='encontrado_onedrive',archivo_origen='onedrive',error=NULL,updated_at=? WHERE id=?").run(now(),row.id); } catch (error) { db.prepare("UPDATE items SET archivo_estado='faltante',error=?,updated_at=? WHERE id=?").run(error instanceof Error ? error.message : "Archivo no encontrado",now(),row.id); } } return true; });
  ipcMain.handle("lotes:send", async (_e, loteId: number) => { const root = normalizePath(setting("onedrive_root")); if (!root) throw new Error("Conecta OneDrive y define la carpeta raíz antes de enviar."); const rows: any[] = db.prepare("SELECT * FROM items WHERE lote_id=? AND envio_estado<>'enviado'").all(loteId); for (const row of rows) { try { let bytes: Buffer; if (row.storage_path) bytes = fs.readFileSync(row.storage_path); else { const full = `/${root}/${normalizePath(row.onedrive_path_esperado)}`; bytes = Buffer.from(await (await graph(`/me/drive/root:${encodeURI(full)}:/content`)).arrayBuffer()); } await sendOutlookMail(row, bytes); db.prepare("UPDATE items SET envio_estado='enviado',sent_at=?,error=NULL,updated_at=? WHERE id=?").run(now(),now(),row.id); } catch (error) { db.prepare("UPDATE items SET envio_estado='error_envio',error=?,updated_at=? WHERE id=?").run(error instanceof Error ? error.message : "No se pudo enviar",now(),row.id); } } const pending = db.prepare("SELECT count(*) AS count FROM items WHERE lote_id=? AND envio_estado<>'enviado'").get(loteId) as { count: number }; db.prepare("UPDATE lotes SET estado=?,sent_at=?,updated_at=? WHERE id=?").run(pending.count ? "error" : "enviado",pending.count ? null : now(),now(),loteId); return true; });
  ipcMain.handle("microsoft:status", microsoftStatus);
  ipcMain.handle("microsoft:configure", (_e, value: string) => { const clientId = z.string().uuid("El Id. de aplicación debe tener formato GUID.").parse(value.trim()); if (fs.existsSync(cachePath())) fs.unlinkSync(cachePath()); setSetting("microsoft_client_id", clientId); configureMsal(); registerMicrosoftProtocol(); return true; });
  ipcMain.handle("microsoft:connect", async () => { if (!msal || !microsoftClientId) throw new Error("Configura primero el Id. de aplicación de Microsoft."); if (authInProgress) return true; authInProgress = true; const url = await msal.getAuthCodeUrl({ scopes: SCOPES, redirectUri: redirectUri() }); await shell.openExternal(url); return true; });
  ipcMain.handle("microsoft:disconnect", async () => { if (fs.existsSync(cachePath())) fs.unlinkSync(cachePath()); setSetting("onedrive_root", ""); configureMsal(); return true; });
  ipcMain.handle("microsoft:set-root", (_e, value: string) => { setSetting("onedrive_root", normalizePath(z.string().max(1000).parse(value))); return true; });
  ipcMain.handle("files:upload", async (_e, itemId: number) => { const selected = await dialog.showOpenDialog(mainWindow!, { properties: ["openFile"], filters: [{ name: "Documentos", extensions: ["pdf","xlsx","xls","xlsm","csv"] }] }); if (selected.canceled || !selected.filePaths[0]) return false; const source = selected.filePaths[0]; if (fs.statSync(source).size > 25 * 1024 * 1024) throw new Error("El archivo no puede superar 25 MB."); const name = path.basename(source).replace(/[^a-zA-Z0-9._-]/g,"_"); const destination = path.join(attachmentsDir(), `${itemId}-${crypto.randomUUID()}-${name}`); fs.copyFileSync(source,destination); db.prepare("UPDATE items SET storage_path=?,storage_original_file_name=?,archivo_origen='manual',archivo_estado='subido_manual',error=NULL,updated_at=? WHERE id=?").run(destination,name,now(),itemId); return true; });
  ipcMain.handle("backup:create", async () => { const selected = await dialog.showSaveDialog(mainWindow!, { defaultPath: `envio-cifras-${new Date().toISOString().slice(0,10)}.sqlite`, filters: [{ name: "SQLite", extensions: ["sqlite","db"] }] }); if (selected.canceled || !selected.filePath) return false; db.pragma("wal_checkpoint(TRUNCATE)"); fs.copyFileSync(dbPath(),selected.filePath); return true; });
  ipcMain.handle("backup:restore", async () => { const selected = await dialog.showOpenDialog(mainWindow!, { properties: ["openFile"], filters: [{ name: "SQLite", extensions: ["sqlite","db"] }] }); if (selected.canceled || !selected.filePaths[0]) return false; const confirmation = await dialog.showMessageBox(mainWindow!, { type: "warning", buttons: ["Cancelar","Restaurar"], defaultId: 0, cancelId: 0, message: "La restauración reemplazará todos los datos locales.", detail: "La aplicación se reiniciará al terminar." }); if (confirmation.response !== 1) return false; const candidate = new Database(selected.filePaths[0], { readonly: true }); try { candidate.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='centros'").get() || (() => { throw new Error("La copia no pertenece a Envío de Cifras."); })(); } finally { candidate.close(); } db.close(); fs.copyFileSync(selected.filePaths[0],dbPath()); app.relaunch(); app.exit(0); return true; });
}
async function handleAuthCallback(url: string) { if (!authInProgress || !msal) return; const params = new URL(url).searchParams; const code = params.get("code"); if (!code) { authInProgress = false; return; } try { await msal.acquireTokenByCode({ code, scopes: SCOPES, redirectUri: redirectUri() }); mainWindow?.webContents.send("microsoft:connected"); } finally { authInProgress = false; } }
function createWindow() { mainWindow = new BrowserWindow({ width: 1500, height: 950, minWidth: 1100, minHeight: 700, backgroundColor: "#edf3f7", webPreferences: { contextIsolation: true, nodeIntegration: false, preload: path.join(__dirname,"preload.cjs") } }); const url = process.env.VITE_DEV_SERVER_URL; if (url) mainWindow.loadURL(url); else mainWindow.loadFile(path.join(__dirname,"../frontend/dist/public/index.html")); }
function configureMenu() { Menu.setApplicationMenu(Menu.buildFromTemplate([{ label: "Archivo", submenu: [{ label: "Crear copia de seguridad", click: () => void mainWindow?.webContents.executeJavaScript("window.envioCifras.backup.create()") }, { type: "separator" }, { label: "Salir", role: "quit" }] }, { label: "Edición", submenu: [{ role: "undo", label: "Deshacer" }, { role: "redo", label: "Rehacer" }, { type: "separator" }, { role: "cut", label: "Cortar" }, { role: "copy", label: "Copiar" }, { role: "paste", label: "Pegar" }, { role: "selectAll", label: "Seleccionar todo" }] }, { label: "Ver", submenu: [{ role: "reload", label: "Recargar" }, { type: "separator" }, { role: "resetZoom", label: "Restablecer zoom" }, { role: "zoomIn", label: "Acercar" }, { role: "zoomOut", label: "Alejar" }] }, { label: "Ventana", submenu: [{ role: "minimize", label: "Minimizar" }, { role: "close", label: "Cerrar" }] }, { label: "Ayuda", submenu: [{ label: "Acerca de Envío de Cifras", click: () => void dialog.showMessageBox(mainWindow!, { type: "info", title: "Envío de Cifras", message: "Envío de Cifras Desktop", detail: "Aplicación local para OneDrive y Outlook." }) }] }])); }
const hasSingleInstanceLock = app.requestSingleInstanceLock();
if (hasSingleInstanceLock) app.whenReady().then(() => { app.setName("Envío de Cifras"); configureMenu(); openDatabase(); configureMsal(); registerMicrosoftProtocol(); registerHandlers(); createWindow(); app.on("activate", () => { if (!BrowserWindow.getAllWindows().length) createWindow(); }); });
else app.quit();
app.on("open-url", (event, url) => { event.preventDefault(); void handleAuthCallback(url); });
app.on("second-instance", (_event, argv) => { const callback = argv.find((value) => value.startsWith("msal") && value.includes("://auth")); if (callback) void handleAuthCallback(callback); mainWindow?.focus(); });
app.on("window-all-closed", () => { if (process.platform !== "darwin") app.quit(); });
