import "dotenv/config";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import express, { type NextFunction, type Request, type Response } from "express";
import cookieParser from "cookie-parser";
import { createPool, type PoolOptions } from "mysql2/promise";
import { z } from "zod";

const app = express();
const port = Number(process.env.PORT || 4180);
const publicUrl = (process.env.PWA_PUBLIC_URL || `http://localhost:${port}`).replace(/\/$/, "");
const installationKey = process.env.PWA_INSTALLATION_KEY?.trim();
const encryptionKey = process.env.PWA_TOKEN_ENCRYPTION_KEY?.trim();
const stateKey = process.env.PWA_STATE_SECRET?.trim() || encryptionKey;
if (!installationKey || !encryptionKey || !stateKey) throw new Error("PWA_INSTALLATION_KEY, PWA_TOKEN_ENCRYPTION_KEY and PWA_STATE_SECRET are required");
const staticDir = path.resolve(process.env.STATIC_DIR || path.resolve(import.meta.dirname, "../../frontend/dist/public"));
const storageDir = path.resolve(process.env.DOCUMENTS_STORAGE_ROOT || path.resolve(import.meta.dirname, "../../../tmp"), "envio-cifras-pwa");
const cookieOptions = { httpOnly: true, secure: process.env.NODE_ENV === "production", sameSite: "lax" as const, maxAge: 180 * 24 * 60 * 60 * 1000, path: "/" };

type DbRow = Record<string, any>;
function databaseConfig(): PoolOptions {
  const url = process.env.DATABASE_URL?.trim();
  if (url) {
    const parsed = new URL(url);
    return { host: parsed.hostname, port: Number(parsed.port || 3306), user: decodeURIComponent(parsed.username), password: decodeURIComponent(parsed.password), database: parsed.pathname.replace(/^\//, "") };
  }
  const required = (name: string) => { const value = process.env[name]?.trim(); if (!value) throw new Error(`${name} is required for MySQL connectivity`); return value; };
  return { host: required("MYSQL_HOST"), port: Number(process.env.MYSQL_PORT || 3306), user: required("MYSQL_USER"), password: required("MYSQL_PASSWORD"), database: required("MYSQL_DATABASE") };
}
const pool = createPool({ ...databaseConfig(), waitForConnections: true, connectionLimit: 10, charset: "utf8mb4" });
const q = async <T extends DbRow = DbRow>(sql: string, values: any[] = []) => (await pool.query(sql, values))[0] as T[] & { insertId?: number; affectedRows?: number };
const json = (value: unknown, fallback: string[] = []) => { try { return typeof value === "string" ? JSON.parse(value) : value ?? fallback; } catch { return fallback; } };
const safePath = (value: string) => value.split("/").filter(Boolean).map(encodeURIComponent).join("/");
const monthName = (month: string) => ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"][Number(month) - 1] || month;
const expectedFile = (year: number, month: string, extension: string) => `DECLARACION VENTAS ${year}.${month}.${extension.replace(/^\./, "")}`;
const greetings = () => Number(new Intl.DateTimeFormat("es-ES", { timeZone: "Europe/Madrid", hour: "numeric", hour12: false }).format()) < 14 ? "Buenos días" : "Buenas tardes";
const render = (template: string, context: Record<string, string>) => template.replace(/\{\{\s*([a-z_]+)\s*\}\}/g, (_m, key) => context[key] ?? "");

function encrypt(value: string) { const iv = crypto.randomBytes(12); const key = crypto.createHash("sha256").update(encryptionKey!).digest(); const cipher = crypto.createCipheriv("aes-256-gcm", key, iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return Buffer.concat([iv, cipher.getAuthTag(), encrypted]).toString("base64"); }
function decrypt(value?: string | null) { if (!value) return null; const raw = Buffer.from(value, "base64"); const key = crypto.createHash("sha256").update(encryptionKey!).digest(); const decipher = crypto.createDecipheriv("aes-256-gcm", key, raw.subarray(0, 12)); decipher.setAuthTag(raw.subarray(12, 28)); return Buffer.concat([decipher.update(raw.subarray(28)), decipher.final()]).toString("utf8"); }
function signState(data: object) { const value = Buffer.from(JSON.stringify(data)).toString("base64url"); return `${value}.${crypto.createHmac("sha256", stateKey!).update(value).digest("base64url")}`; }
function parseState(raw: string) { const [value, signature] = raw.split("."); const expected = crypto.createHmac("sha256", stateKey!).update(value).digest("base64url"); if (!value || !signature || !crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) throw new Error("Estado OAuth inválido"); const parsed = JSON.parse(Buffer.from(value, "base64url").toString("utf8")); if (Date.now() - parsed.ts > 15 * 60_000) throw new Error("La conexión Microsoft ha caducado"); return parsed as { deviceId: string; installHash: string; ts: number }; }
function installationHash() { return crypto.createHash("sha256").update(installationKey!).digest("hex"); }
function getDevice(req: Request, res: Response) { let deviceId = req.cookies?.ec_device; if (!deviceId) { deviceId = crypto.randomBytes(24).toString("hex"); res.cookie("ec_device", deviceId, cookieOptions); } return deviceId as string; }

async function ensureSchema() {
  await q(`CREATE TABLE IF NOT EXISTS EC_centros (id INT AUTO_INCREMENT PRIMARY KEY, parque_centro VARCHAR(255) NOT NULL, localidad VARCHAR(255) NOT NULL, email_primario VARCHAR(255) NOT NULL, email_secundario VARCHAR(255) NULL, onedrive_folder_path VARCHAR(1000) NULL, activo BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3))`);
  await q(`CREATE TABLE IF NOT EXISTS EC_templates (id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(255) NOT NULL, asunto_template LONGTEXT NOT NULL, cuerpo_template LONGTEXT NOT NULL, saludo_default VARCHAR(120) NULL, activo BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3))`);
  await q(`CREATE TABLE IF NOT EXISTS EC_lotes (id INT AUTO_INCREMENT PRIMARY KEY, anio INT NOT NULL, mes_numero VARCHAR(2) NOT NULL, mes_nombre VARCHAR(40) NOT NULL, extension_archivo VARCHAR(20) NOT NULL, template_id INT NOT NULL, estado VARCHAR(30) NOT NULL DEFAULT 'borrador', sent_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), UNIQUE KEY ec_lote_periodo (anio, mes_numero, extension_archivo))`);
  await q(`CREATE TABLE IF NOT EXISTS EC_items (id INT AUTO_INCREMENT PRIMARY KEY, lote_id INT NOT NULL, centro_id INT NULL, parque_centro_snapshot VARCHAR(255) NOT NULL, localidad_snapshot VARCHAR(255) NOT NULL, destinatarios_json LONGTEXT NOT NULL, asunto LONGTEXT NOT NULL, cuerpo LONGTEXT NOT NULL, archivo_nombre VARCHAR(255) NOT NULL, onedrive_path_esperado VARCHAR(1000) NULL, storage_path VARCHAR(1000) NULL, storage_original_file_name VARCHAR(255) NULL, archivo_origen VARCHAR(20) NOT NULL DEFAULT 'ninguno', archivo_estado VARCHAR(30) NOT NULL DEFAULT 'pendiente', envio_estado VARCHAR(30) NOT NULL DEFAULT 'pendiente', error LONGTEXT NULL, sent_at DATETIME(3) NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), INDEX ec_items_lote (lote_id))`);
  await q(`CREATE TABLE IF NOT EXISTS EC_integrations (id INT AUTO_INCREMENT PRIMARY KEY, device_id VARCHAR(128) NOT NULL, access_token_encrypted LONGTEXT NULL, refresh_token_encrypted LONGTEXT NULL, expires_at DATETIME(3) NULL, account_email VARCHAR(255) NULL, root_path VARCHAR(1000) NULL, status VARCHAR(30) NOT NULL DEFAULT 'disconnected', created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3), UNIQUE KEY ec_integration_device (device_id))`);
  const templates = await q("SELECT id FROM EC_templates LIMIT 1");
  if (!templates.length) await q("INSERT INTO EC_templates (nombre, asunto_template, cuerpo_template, saludo_default) VALUES (?, ?, ?, ?)", ["Plantilla BOOM por defecto", "Muebles BOOM ♥ - {{localidad}} - {{parque_centro}} - Cifra de ventas - {{mes_nombre}} {{anio}}", "{{saludo}},\n\nAdjuntamos archivo con la cifra de ventas realizada durante el periodo correspondiente en el local arrendado de {{parque_centro}}.\n\nSaludos,\n\nMuebles BOOM ♥", null]);
}

async function integration(deviceId: string) { return (await q("SELECT * FROM EC_integrations WHERE device_id = ? LIMIT 1", [deviceId]))[0] as DbRow | undefined; }
function microsoftConfig() { const clientId = process.env.MICROSOFT_CLIENT_ID?.trim(); const clientSecret = process.env.MICROSOFT_CLIENT_SECRET?.trim(); if (!clientId || !clientSecret) throw new Error("Microsoft no está configurado en esta instalación"); return { clientId, clientSecret, tenant: process.env.MICROSOFT_TENANT_ID?.trim() || "common", redirect: process.env.MICROSOFT_REDIRECT_URI?.trim() || `${publicUrl}/api/microsoft/callback` }; }
async function tokenFor(deviceId: string) { const row = await integration(deviceId); if (!row || row.status !== "connected") throw new Error("Conecta OneDrive y Outlook antes de continuar"); if (row.expires_at && new Date(row.expires_at).getTime() > Date.now() + 60_000) return decrypt(row.access_token_encrypted)!; const refresh = decrypt(row.refresh_token_encrypted); if (!refresh) throw new Error("La conexión Microsoft debe renovarse"); const cfg = microsoftConfig(); const response = await fetch(`https://login.microsoftonline.com/${cfg.tenant}/oauth2/v2.0/token`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: cfg.clientId, client_secret: cfg.clientSecret, grant_type: "refresh_token", refresh_token: refresh }) }); const data = await response.json() as any; if (!response.ok || !data.access_token) throw new Error(data.error_description || "No se pudo renovar la conexión Microsoft"); await q("UPDATE EC_integrations SET access_token_encrypted=?, expires_at=? WHERE device_id=?", [encrypt(data.access_token), new Date(Date.now() + Number(data.expires_in || 3600) * 1000), deviceId]); return data.access_token as string; }
async function graph(deviceId: string, pathName: string, init: RequestInit = {}) { const token = await tokenFor(deviceId); const response = await fetch(`https://graph.microsoft.com/v1.0${pathName}`, { ...init, headers: { authorization: `Bearer ${token}`, ...(init.headers || {}) } }); if (!response.ok) { const data = await response.json().catch(() => ({})) as any; throw new Error(data.error?.message || "Microsoft Graph no pudo completar la operación"); } return response; }
async function sendSmtpMail(input: { to: string[]; subject: string; text: string; filename: string; content: Buffer }) {
  const host = process.env.SMTP_HOST?.trim();
  const port = Number(process.env.SMTP_PORT || "25");
  const user = process.env.SMTP_USER?.trim();
  const pass = process.env.SMTP_PASS;
  const from = (process.env.SMTP_FROM || user || "").trim();
  if (!host || !from || Number.isNaN(port)) throw new Error("SMTP no está configurado en esta instalación");
  const mode = process.env.EMAIL_MODE === "production" ? "production" : "test";
  const intended = input.to.join(", ");
  const recipient = mode === "test" ? (process.env.EMAIL_TEST_RECIPIENT || "") : intended;
  if (!recipient) throw new Error("EMAIL_TEST_RECIPIENT es obligatorio mientras EMAIL_MODE no sea production");
  const nodemailer = await import("nodemailer");
  const transporter = nodemailer.default.createTransport({ host, port, secure: process.env.SMTP_SECURE === "true" || port === 465, auth: user && pass ? { user, pass } : undefined, ignoreTLS: process.env.SMTP_IGNORE_TLS === "true", requireTLS: process.env.SMTP_REQUIRE_TLS === "true" });
  await transporter.sendMail({ from: `"${process.env.SMTP_FROM_NAME || "Muebles BOOM"}" <${from}>`, to: recipient, subject: input.subject, text: mode === "test" ? `MODO PRUEBA: este correo habría sido enviado a ${intended}.\n\n${input.text}` : input.text, attachments: [{ filename: input.filename, content: input.content }] });
}
function normalizePath(value?: string | null) { const pathName = (value || "").trim().replace(/\\/g, "/").replace(/^\/+|\/+$/g, ""); return pathName ? `/${pathName}` : ""; }
function mapCentro(row: DbRow) { return { id: row.id, parqueCentro: row.parque_centro, localidad: row.localidad, emailPrimario: row.email_primario, emailSecundario: row.email_secundario, oneDriveFolderPath: row.onedrive_folder_path, activo: !!row.activo }; }
function mapTemplate(row: DbRow) { return { id: row.id, nombre: row.nombre, asuntoTemplate: row.asunto_template, cuerpoTemplate: row.cuerpo_template, saludoDefault: row.saludo_default, activo: !!row.activo }; }
function mapItem(row: DbRow) { return { id: row.id, parqueCentroSnapshot: row.parque_centro_snapshot, localidadSnapshot: row.localidad_snapshot, destinatarios: json(row.destinatarios_json), asunto: row.asunto, cuerpo: row.cuerpo, archivoNombre: row.archivo_nombre, oneDrivePathEsperado: row.onedrive_path_esperado, storageOriginalFileName: row.storage_original_file_name, archivoEstado: row.archivo_estado, envioEstado: row.envio_estado, error: row.error }; }
function mapLote(row: DbRow) { return { id: row.id, anio: row.anio, mesNumero: row.mes_numero, mesNombre: row.mes_nombre, extensionArchivo: row.extension_archivo, estado: row.estado }; }

app.set("trust proxy", 1); app.use(cookieParser()); app.use(express.json({ limit: "1mb" }));
app.get("/api/healthz", (_req, res) => res.json({ ok: true }));
app.get("/access/:key", (req, res) => { if (!crypto.timingSafeEqual(Buffer.from(req.params.key), Buffer.from(installationKey!))) return res.status(404).end(); res.cookie("ec_install", installationHash(), cookieOptions); res.redirect("/"); });
app.use("/api", (req, res, next) => { if (req.cookies?.ec_install !== installationHash()) return res.status(401).json({ message: "Abre la aplicación desde el enlace privado de la empresa." }); getDevice(req, res); next(); });

const centroSchema = z.object({ parqueCentro: z.string().trim().min(2), localidad: z.string().trim().min(2), emailPrimario: z.string().trim().email(), emailSecundario: z.string().trim().email().or(z.literal("")).optional(), oneDriveFolderPath: z.string().trim().optional(), activo: z.coerce.boolean().optional() });
const templateSchema = z.object({ nombre: z.string().trim().min(2), asuntoTemplate: z.string().trim().min(2), cuerpoTemplate: z.string().trim().min(2), saludoDefault: z.string().trim().optional(), activo: z.coerce.boolean().optional() });
app.get("/api/centros", async (_req, res, next) => { try { res.json({ data: (await q("SELECT * FROM EC_centros ORDER BY parque_centro")).map(mapCentro) }); } catch (e) { next(e); } });
app.post("/api/centros", async (req, res, next) => { try { const value = centroSchema.parse(req.body); const result = await q("INSERT INTO EC_centros (parque_centro, localidad, email_primario, email_secundario, onedrive_folder_path, activo) VALUES (?, ?, ?, ?, ?, ?)", [value.parqueCentro, value.localidad, value.emailPrimario, value.emailSecundario || null, value.oneDriveFolderPath || null, value.activo ?? true]); res.status(201).json({ id: result.insertId }); } catch (e) { next(e); } });
app.put("/api/centros/:id", async (req, res, next) => { try { const value = centroSchema.parse(req.body); await q("UPDATE EC_centros SET parque_centro=?, localidad=?, email_primario=?, email_secundario=?, onedrive_folder_path=?, activo=? WHERE id=?", [value.parqueCentro, value.localidad, value.emailPrimario, value.emailSecundario || null, value.oneDriveFolderPath || null, value.activo ?? true, Number(req.params.id)]); res.json({ ok: true }); } catch (e) { next(e); } });
app.get("/api/templates", async (_req, res, next) => { try { res.json({ data: (await q("SELECT * FROM EC_templates ORDER BY nombre")).map(mapTemplate) }); } catch (e) { next(e); } });
app.post("/api/templates", async (req, res, next) => { try { const value = templateSchema.parse(req.body); const result = await q("INSERT INTO EC_templates (nombre, asunto_template, cuerpo_template, saludo_default, activo) VALUES (?, ?, ?, ?, ?)", [value.nombre, value.asuntoTemplate, value.cuerpoTemplate, value.saludoDefault || null, value.activo ?? true]); res.status(201).json({ id: result.insertId }); } catch (e) { next(e); } });
app.put("/api/templates/:id", async (req, res, next) => { try { const value = templateSchema.parse(req.body); await q("UPDATE EC_templates SET nombre=?, asunto_template=?, cuerpo_template=?, saludo_default=?, activo=? WHERE id=?", [value.nombre, value.asuntoTemplate, value.cuerpoTemplate, value.saludoDefault || null, value.activo ?? true, Number(req.params.id)]); res.json({ ok: true }); } catch (e) { next(e); } });

app.get("/api/lotes", async (_req, res, next) => { try { res.json({ data: (await q("SELECT * FROM EC_lotes ORDER BY anio DESC, mes_numero DESC, created_at DESC")).map(mapLote) }); } catch (e) { next(e); } });
app.get("/api/lotes/:id", async (req, res, next) => { try { const lote = (await q("SELECT * FROM EC_lotes WHERE id=?", [Number(req.params.id)]))[0]; if (!lote) return res.status(404).json({ message: "Lote no encontrado" }); res.json({ ...mapLote(lote), items: (await q("SELECT * FROM EC_items WHERE lote_id=? ORDER BY parque_centro_snapshot", [lote.id])).map(mapItem) }); } catch (e) { next(e); } });
app.post("/api/lotes", async (req, res, next) => { try { const body = z.object({ anio: z.number().int().min(2000).max(2100), mesNumero: z.string().regex(/^0?[1-9]$|^1[0-2]$/), extensionArchivo: z.string().trim().min(1).max(20), templateId: z.number().int().positive() }).parse(req.body); const month = String(Number(body.mesNumero)).padStart(2, "0"); const template = (await q("SELECT * FROM EC_templates WHERE id=?", [body.templateId]))[0]; if (!template) throw new Error("Plantilla no encontrada"); const existing = (await q("SELECT * FROM EC_lotes WHERE anio=? AND mes_numero=? AND extension_archivo=?", [body.anio, month, body.extensionArchivo.replace(/^\./, "").toLowerCase()]))[0]; if (existing) return res.json(mapLote(existing)); const result = await q("INSERT INTO EC_lotes (anio, mes_numero, mes_nombre, extension_archivo, template_id) VALUES (?, ?, ?, ?, ?)", [body.anio, month, monthName(month), body.extensionArchivo.replace(/^\./, "").toLowerCase(), body.templateId]); const centers = await q("SELECT * FROM EC_centros WHERE activo=1 ORDER BY parque_centro"); for (const center of centers) { const fileName = expectedFile(body.anio, month, body.extensionArchivo); const context = { saludo: template.saludo_default || greetings(), parque_centro: center.parque_centro, localidad: center.localidad, mes_nombre: monthName(month), mes_numero: month, anio: String(body.anio), archivo_nombre: fileName }; const relative = `${normalizePath(center.onedrive_folder_path)}/${fileName}`; await q("INSERT INTO EC_items (lote_id, centro_id, parque_centro_snapshot, localidad_snapshot, destinatarios_json, asunto, cuerpo, archivo_nombre, onedrive_path_esperado) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [result.insertId, center.id, center.parque_centro, center.localidad, JSON.stringify([center.email_primario, center.email_secundario].filter(Boolean)), render(template.asunto_template, context), render(template.cuerpo_template, context), fileName, relative]); } const created = (await q("SELECT * FROM EC_lotes WHERE id=?", [result.insertId]))[0]; res.status(201).json(mapLote(created)); } catch (e) { next(e); } });

app.get("/api/microsoft/status", async (req, res, next) => { try { const row = await integration(getDevice(req, res)); res.json({ connected: row?.status === "connected", accountEmail: row?.account_email || null, rootPath: row?.root_path || null }); } catch (e) { next(e); } });
app.get("/api/microsoft/connect", (req, res, next) => { try { const cfg = microsoftConfig(); const state = signState({ deviceId: getDevice(req, res), installHash: installationHash(), ts: Date.now() }); const params = new URLSearchParams({ client_id: cfg.clientId, response_type: "code", redirect_uri: cfg.redirect, response_mode: "query", scope: "offline_access User.Read Files.Read", state }); res.redirect(`https://login.microsoftonline.com/${cfg.tenant}/oauth2/v2.0/authorize?${params}`); } catch (e) { next(e); } });
app.get("/api/microsoft/callback", async (req, res) => { try { const code = String(req.query.code || ""); const state = parseState(String(req.query.state || "")); if (!code || state.installHash !== installationHash()) throw new Error("La conexión no pertenece a esta instalación"); const cfg = microsoftConfig(); const response = await fetch(`https://login.microsoftonline.com/${cfg.tenant}/oauth2/v2.0/token`, { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: cfg.clientId, client_secret: cfg.clientSecret, grant_type: "authorization_code", code, redirect_uri: cfg.redirect }) }); const data = await response.json() as any; if (!response.ok || !data.access_token || !data.refresh_token) throw new Error(data.error_description || "Microsoft no devolvió credenciales válidas"); const profileResponse = await fetch("https://graph.microsoft.com/v1.0/me", { headers: { authorization: `Bearer ${data.access_token}` } }); const profile = await profileResponse.json() as any; if (!profileResponse.ok) throw new Error("No se pudo consultar la cuenta Microsoft"); await q("INSERT INTO EC_integrations (device_id, access_token_encrypted, refresh_token_encrypted, expires_at, account_email, status) VALUES (?, ?, ?, ?, ?, 'connected') ON DUPLICATE KEY UPDATE access_token_encrypted=VALUES(access_token_encrypted), refresh_token_encrypted=VALUES(refresh_token_encrypted), expires_at=VALUES(expires_at), account_email=VALUES(account_email), status='connected'", [state.deviceId, encrypt(data.access_token), encrypt(data.refresh_token), new Date(Date.now() + Number(data.expires_in || 3600) * 1000), profile.mail || profile.userPrincipalName || null]); res.cookie("ec_install", installationHash(), cookieOptions); res.cookie("ec_device", state.deviceId, cookieOptions); res.redirect("/?microsoft=connected"); } catch (error) { res.redirect(`/?microsoft=error&message=${encodeURIComponent(error instanceof Error ? error.message : "Error")}`); } });
app.put("/api/microsoft/root", async (req, res, next) => { try { const root = z.object({ rootPath: z.string().max(1000) }).parse(req.body).rootPath; const device = getDevice(req, res); if (!(await integration(device))) throw new Error("Conecta Microsoft antes de elegir una carpeta"); await q("UPDATE EC_integrations SET root_path=? WHERE device_id=?", [normalizePath(root) || null, device]); res.json({ ok: true }); } catch (e) { next(e); } });

app.post("/api/lotes/:id/search-onedrive", async (req, res, next) => { try { const device = getDevice(req, res); const row = await integration(device); if (!row?.root_path) throw new Error("Selecciona primero la carpeta raíz de OneDrive"); const items = await q("SELECT * FROM EC_items WHERE lote_id=?", [Number(req.params.id)]); for (const item of items) { const fullPath = `${normalizePath(row.root_path)}${normalizePath(item.onedrive_path_esperado)}`; try { await graph(device, `/me/drive/root:${safePath(fullPath)}:`); await q("UPDATE EC_items SET archivo_estado='encontrado_onedrive', archivo_origen='onedrive', error=NULL WHERE id=?", [item.id]); } catch (error) { await q("UPDATE EC_items SET archivo_estado='faltante', error=? WHERE id=?", [error instanceof Error ? error.message : "Archivo no encontrado", item.id]); } } res.json({ ok: true }); } catch (e) { next(e); } });
app.post("/api/items/:id/upload", express.raw({ type: "*/*", limit: "25mb" }), async (req, res, next) => { try { const name = path.basename(String(req.header("x-file-name") || "archivo")).replace(/[^a-zA-Z0-9._-]/g, "_"); const extension = path.extname(name).toLowerCase(); if (!new Set([".pdf", ".xlsx", ".xls", ".xlsm", ".csv"]).has(extension) || !Buffer.isBuffer(req.body)) throw new Error("Archivo no permitido"); await mkdir(storageDir, { recursive: true }); const stored = `${req.params.id}-${Date.now()}-${crypto.randomUUID()}-${name}`; const destination = path.resolve(storageDir, stored); if (!destination.startsWith(storageDir + path.sep)) throw new Error("Ruta de archivo inválida"); await writeFile(destination, req.body); await q("UPDATE EC_items SET storage_path=?, storage_original_file_name=?, archivo_origen='manual', archivo_estado='subido_manual', error=NULL WHERE id=?", [destination, name, Number(req.params.id)]); res.json({ ok: true }); } catch (e) { next(e); } });
app.post("/api/lotes/:id/send", async (req, res, next) => { try { const device = getDevice(req, res); const integrationRow = await integration(device); if (!integrationRow?.root_path) throw new Error("Conecta OneDrive y selecciona la carpeta raíz antes de enviar"); const items = await q("SELECT * FROM EC_items WHERE lote_id=? AND envio_estado <> 'enviado'", [Number(req.params.id)]); for (const item of items) { try { let content: Buffer; if (item.storage_path) content = await readFile(item.storage_path); else { const fullPath = `${normalizePath(integrationRow.root_path)}${normalizePath(item.onedrive_path_esperado)}`; const response = await graph(device, `/me/drive/root:${safePath(fullPath)}:/content`); content = Buffer.from(await response.arrayBuffer()); } await sendSmtpMail({ to: json(item.destinatarios_json), subject: item.asunto, text: item.cuerpo, filename: item.storage_original_file_name || item.archivo_nombre, content }); await q("UPDATE EC_items SET envio_estado='enviado', sent_at=NOW(3), error=NULL WHERE id=?", [item.id]); } catch (error) { await q("UPDATE EC_items SET envio_estado='error_envio', error=? WHERE id=?", [error instanceof Error ? error.message : "No se pudo enviar", item.id]); } } const pending = await q("SELECT id FROM EC_items WHERE lote_id=? AND envio_estado <> 'enviado'", [Number(req.params.id)]); await q("UPDATE EC_lotes SET estado=?, sent_at=? WHERE id=?", [pending.length ? "error" : "enviado", pending.length ? null : new Date(), Number(req.params.id)]); res.json({ ok: true }); } catch (e) { next(e); } });

app.use((error: any, _req: Request, res: Response, _next: NextFunction) => { console.error(error); res.status(error instanceof z.ZodError ? 400 : 500).json({ message: error instanceof Error ? error.message : "Error interno" }); });
if (fs.existsSync(path.join(staticDir, "index.html"))) { app.use(express.static(staticDir)); app.get("*splat", (_req, res) => res.sendFile(path.join(staticDir, "index.html"))); }
ensureSchema().then(() => app.listen(port, () => console.log(`Envio cifras PWA on ${port}`))).catch((error) => { console.error(error); process.exit(1); });
