import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Cloud, FileUp, History, Mail, Plus, RefreshCw, Send, Settings, Users } from "lucide-react";
import "./styles.css";

type Centro = { id: number; parqueCentro: string; localidad: string; emailPrimario: string; emailSecundario?: string | null; oneDriveFolderPath?: string | null; activo: boolean };
type Template = { id: number; nombre: string; asuntoTemplate: string; cuerpoTemplate: string; saludoDefault?: string | null; activo: boolean };
type Item = { id: number; parqueCentroSnapshot: string; localidadSnapshot: string; destinatarios: string[]; archivoNombre: string; archivoEstado: string; envioEstado: string; error?: string | null; oneDrivePathEsperado?: string | null; storageOriginalFileName?: string | null };
type Lote = { id: number; anio: number; mesNumero: string; mesNombre: string; extensionArchivo: string; estado: string; items?: Item[] };
type MicrosoftStatus = { connected: boolean; accountEmail?: string | null; rootPath?: string | null };

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api${path}`, { credentials: "include", ...init });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || "No se pudo completar la operación.");
  return data as T;
}

const madridNow = () => {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Madrid", year: "numeric", month: "2-digit" }).formatToParts();
  const read = (kind: string) => parts.find((part) => part.type === kind)?.value ?? "";
  return { anio: Number(read("year")), mes: read("month") };
};
const monthName = (month: string) => new Intl.DateTimeFormat("es-ES", { month: "long" }).format(new Date(2026, Number(month) - 1, 1));

function App() {
  const client = useQueryClient();
  const [tab, setTab] = useState<"envio" | "centros" | "plantillas" | "historial" | "conexion">("envio");
  const [selectedLoteId, setSelectedLoteId] = useState<number | null>(null);
  const [notice, setNotice] = useState<string>("");
  const centros = useQuery({ queryKey: ["centros"], queryFn: () => api<{ data: Centro[] }>("/centros") });
  const templates = useQuery({ queryKey: ["templates"], queryFn: () => api<{ data: Template[] }>("/templates") });
  const lotes = useQuery({ queryKey: ["lotes"], queryFn: () => api<{ data: Lote[] }>("/lotes") });
  const connection = useQuery({ queryKey: ["microsoft"], queryFn: () => api<MicrosoftStatus>("/microsoft/status") });
  const detail = useQuery({ queryKey: ["lote", selectedLoteId], enabled: !!selectedLoteId, queryFn: () => api<Lote>(`/lotes/${selectedLoteId}`) });
  useEffect(() => { if (!selectedLoteId && lotes.data?.data[0]) setSelectedLoteId(lotes.data.data[0].id); }, [lotes.data, selectedLoteId]);
  useEffect(() => { const result = new URLSearchParams(location.search).get("microsoft"); if (result) { setNotice(result === "connected" ? "Microsoft conectado correctamente." : "No se pudo conectar Microsoft."); history.replaceState({}, "", location.pathname); void connection.refetch(); } }, [connection]);
  const refresh = () => void Promise.all(["centros", "templates", "lotes", "lote", "microsoft"].map((key) => client.invalidateQueries({ queryKey: [key] })));
  const selected = detail.data;
  const send = useMutation({ mutationFn: () => api(`/lotes/${selectedLoteId}/send`, { method: "POST" }), onSuccess: () => { setNotice("Envío procesado."); refresh(); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Error de envío") });
  const search = useMutation({ mutationFn: () => api(`/lotes/${selectedLoteId}/search-onedrive`, { method: "POST" }), onSuccess: () => { setNotice("Archivos comprobados en OneDrive."); refresh(); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Error al buscar") });
  const createLote = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const lote = await api<Lote>("/lotes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ anio: Number(form.get("anio")), mesNumero: form.get("mesNumero"), extensionArchivo: form.get("extensionArchivo"), templateId: Number(form.get("templateId")) }) }); setSelectedLoteId(lote.id); setNotice("Período generado correctamente."); refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo generar el período"); } };
  const upload = async (itemId: number, file: File) => { try { await api(`/items/${itemId}/upload`, { method: "POST", headers: { "content-type": file.type || "application/octet-stream", "x-file-name": file.name }, body: file }); setNotice("Archivo subido."); refresh(); } catch (e) { setNotice(e instanceof Error ? e.message : "No se pudo subir"); } };
  return <main><header><div className="brand"><span>BOOM</span><small>Envío de cifras</small></div><div className="connection"><Cloud size={18}/>{connection.data?.connected ? connection.data.accountEmail : "Microsoft sin conectar"}</div></header>
    <nav>{([["envio", Send, "Enviar"], ["centros", Users, "Centros"], ["plantillas", Mail, "Plantillas"], ["historial", History, "Historial"], ["conexion", Settings, "Conexión"]] as const).map(([id, Icon, label]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}><Icon size={18}/>{label}</button>)}</nav>
    {notice && <div className="notice" role="status">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    {tab === "envio" && <section className="grid"><article className="panel"><h1>Nuevo período</h1><p>Genera una fila por cada centro activo.</p><LoteForm templates={templates.data?.data ?? []} onSubmit={createLote}/></article><article className="panel"><h1>Lotes</h1><div className="list">{(lotes.data?.data ?? []).map((lote) => <button className={selectedLoteId === lote.id ? "selected" : ""} onClick={() => setSelectedLoteId(lote.id)} key={lote.id}>{lote.mesNombre} {lote.anio}<small>{lote.estado}</small></button>) || "Sin lotes"}</div></article>
      <article className="panel wide"><div className="actions"><div><h1>{selected ? `${selected.mesNombre} ${selected.anio}` : "Selecciona un lote"}</h1><p>{selected?.items?.length ?? 0} centros en el período.</p></div><div><button disabled={!selected || search.isPending} onClick={() => search.mutate()}><RefreshCw size={16}/>Buscar en OneDrive</button><button className="primary" disabled={!selected || send.isPending} onClick={() => send.mutate()}><Send size={16}/>{send.isPending ? "Enviando…" : "Enviar listos"}</button></div></div><Items items={selected?.items ?? []} onUpload={upload}/></article></section>}
    {tab === "centros" && <Centros data={centros.data?.data ?? []} done={refresh} message={setNotice}/>} {tab === "plantillas" && <Plantillas data={templates.data?.data ?? []} done={refresh} message={setNotice}/>} {tab === "historial" && <Historico lotes={lotes.data?.data ?? []}/>} {tab === "conexion" && <Conexion status={connection.data} done={refresh} message={setNotice}/>} </main>;
}

function LoteForm({ templates, onSubmit }: { templates: Template[]; onSubmit: (e: React.FormEvent<HTMLFormElement>) => void }) { const now = madridNow(); return <form onSubmit={onSubmit} className="form compact"><label>Año<input name="anio" defaultValue={now.anio}/></label><label>Mes<select name="mesNumero" defaultValue={now.mes}>{Array.from({ length: 12 }, (_, i) => { const value = String(i + 1).padStart(2, "0"); return <option value={value} key={value}>{monthName(value)} ({value})</option>; })}</select></label><label>Extensión<input name="extensionArchivo" defaultValue="pdf"/></label><label>Plantilla<select name="templateId">{templates.filter((t) => t.activo).map((t) => <option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><button className="primary" type="submit"><Plus size={16}/>Generar período</button></form>; }
function Items({ items, onUpload }: { items: Item[]; onUpload: (id: number, file: File) => void }) { return <div className="table-wrap"><table><thead><tr><th>Centro</th><th>Destinatarios</th><th>Archivo</th><th>Estado</th><th>Alternativa</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.parqueCentroSnapshot}<small>{item.localidadSnapshot}</small></td><td>{item.destinatarios.join(", ")}</td><td>{item.storageOriginalFileName || item.oneDrivePathEsperado || item.archivoNombre}</td><td><span className={`pill ${item.envioEstado === "enviado" ? "ok" : item.archivoEstado === "faltante" ? "bad" : ""}`}>{item.envioEstado === "enviado" ? "Enviado" : item.archivoEstado}</span>{item.error && <small className="error">{item.error}</small>}</td><td><label className="upload"><FileUp size={15}/>Subir<input type="file" accept=".pdf,.xlsx,.xls,.xlsm,.csv" onChange={(e) => e.target.files?.[0] && onUpload(item.id, e.target.files[0])}/></label></td></tr>)}</tbody></table></div>; }
function Centros({ data, done, message }: { data: Centro[]; done: () => void; message: (value: string) => void }) { const [editing, setEditing] = useState<Partial<Centro> | null>(null); const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); const body = Object.fromEntries(f); try { await api(editing?.id ? `/centros/${editing.id}` : "/centros", { method: editing?.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setEditing(null); done(); message("Centro guardado."); } catch (error) { message(error instanceof Error ? error.message : "Error al guardar"); } }; return <section className="panel"><div className="actions"><div><h1>Centros</h1><p>Destinatarios y carpeta relativa de cada centro.</p></div><button className="primary" onClick={() => setEditing({ activo: true })}><Plus size={16}/>Añadir centro</button></div>{editing && <form className="form" onSubmit={save}><input name="parqueCentro" placeholder="Parque / centro" defaultValue={editing.parqueCentro}/><input name="localidad" placeholder="Localidad" defaultValue={editing.localidad}/><input name="emailPrimario" placeholder="Email principal" defaultValue={editing.emailPrimario}/><input name="emailSecundario" placeholder="Email secundario" defaultValue={editing.emailSecundario ?? ""}/><input name="oneDriveFolderPath" placeholder="Carpeta dentro de la raíz" defaultValue={editing.oneDriveFolderPath ?? ""}/><button className="primary">Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form>}<div className="table-wrap"><table><thead><tr><th>Centro</th><th>Localidad</th><th>Correos</th><th>Carpeta OneDrive</th><th></th></tr></thead><tbody>{data.map((row) => <tr key={row.id}><td>{row.parqueCentro}</td><td>{row.localidad}</td><td>{[row.emailPrimario, row.emailSecundario].filter(Boolean).join(", ")}</td><td>{row.oneDriveFolderPath || "—"}</td><td><button onClick={() => setEditing(row)}>Editar</button></td></tr>)}</tbody></table></div></section>; }
function Plantillas({ data, done, message }: { data: Template[]; done: () => void; message: (value: string) => void }) { const [editing, setEditing] = useState<Partial<Template> | null>(null); const save = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api(editing?.id ? `/templates/${editing.id}` : "/templates", { method: editing?.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(f)) }); setEditing(null); done(); message("Plantilla guardada."); } catch (error) { message(error instanceof Error ? error.message : "Error al guardar"); } }; return <section className="panel"><div className="actions"><div><h1>Plantillas</h1><p>Variables: {"{{saludo}}, {{localidad}}, {{parque_centro}}, {{mes_nombre}}, {{anio}}"}</p></div><button className="primary" onClick={() => setEditing({ activo: true })}><Plus size={16}/>Añadir plantilla</button></div>{editing && <form className="form vertical" onSubmit={save}><input name="nombre" placeholder="Nombre" defaultValue={editing.nombre}/><input name="asuntoTemplate" placeholder="Asunto" defaultValue={editing.asuntoTemplate}/><textarea name="cuerpoTemplate" placeholder="Cuerpo" defaultValue={editing.cuerpoTemplate}/><input name="saludoDefault" placeholder="Saludo opcional" defaultValue={editing.saludoDefault ?? ""}/><button className="primary">Guardar</button><button type="button" onClick={() => setEditing(null)}>Cancelar</button></form>}<div className="table-wrap"><table><thead><tr><th>Nombre</th><th>Asunto</th><th>Vista previa</th><th></th></tr></thead><tbody>{data.map((row) => <tr key={row.id}><td>{row.nombre}</td><td>{row.asuntoTemplate}</td><td>{row.cuerpoTemplate}</td><td><button onClick={() => setEditing(row)}>Editar</button></td></tr>)}</tbody></table></div></section>; }
function Historico({ lotes }: { lotes: Lote[] }) { return <section className="panel"><h1>Histórico</h1><div className="table-wrap"><table><thead><tr><th>Periodo</th><th>Extensión</th><th>Estado</th></tr></thead><tbody>{lotes.map((lote) => <tr key={lote.id}><td>{lote.mesNombre} {lote.anio}</td><td>{lote.extensionArchivo}</td><td>{lote.estado}</td></tr>)}</tbody></table></div></section>; }
function Conexion({ status, done, message }: { status?: MicrosoftStatus; done: () => void; message: (value: string) => void }) { const [root, setRoot] = useState(status?.rootPath ?? ""); useEffect(() => setRoot(status?.rootPath ?? ""), [status?.rootPath]); const saveRoot = async () => { try { await api("/microsoft/root", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ rootPath: root }) }); done(); message("Carpeta raíz actualizada."); } catch (error) { message(error instanceof Error ? error.message : "Error al guardar"); } }; return <section className="panel connection-panel"><h1>OneDrive</h1><p>Conecta tu cuenta Microsoft para leer los archivos de tu OneDrive. Los correos se envían temporalmente mediante el SMTP configurado.</p><p><b>Estado:</b> {status?.connected ? `Conectado como ${status.accountEmail}` : "Sin conectar"}</p>{status?.connected ? <><label>Carpeta raíz OneDrive<input value={root} onChange={(e) => setRoot(e.target.value)} placeholder="/Cifras"/></label><button className="primary" onClick={saveRoot}>Guardar carpeta</button></> : <button className="primary" onClick={() => { location.href = "/api/microsoft/connect" }}><Cloud size={16}/>Conectar OneDrive</button>}</section>; }

if ("serviceWorker" in navigator) window.addEventListener("load", () => void navigator.serviceWorker.register("/sw.js"));
createRoot(document.getElementById("root")!).render(<QueryClientProvider client={new QueryClient()}><App/></QueryClientProvider>);
