import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, CheckCircle2, ChevronLeft, Cloud, FileSpreadsheet, FileUp, History, Menu, Pencil, Plus, RefreshCw, Send, X } from "lucide-react";
import "./styles.css";

type Centro = { id: number; parqueCentro: string; localidad: string; emailPrimario: string; emailSecundario?: string | null; oneDriveFolderPath?: string | null; activo: boolean };
type Template = { id: number; nombre: string; asuntoTemplate: string; cuerpoTemplate: string; saludoDefault?: string | null; activo: boolean };
type Item = { id: number; parqueCentroSnapshot: string; localidadSnapshot: string; destinatarios: string[]; asunto: string; cuerpo: string; archivoNombre: string; archivoEstado: string; envioEstado: string; error?: string | null; oneDrivePathEsperado?: string | null; storageOriginalFileName?: string | null };
type Lote = { id: number; anio: number; mesNumero: string; mesNombre: string; extensionArchivo: string; estado: string; items?: Item[] };
type MicrosoftStatus = { connected: boolean; accountEmail?: string | null; rootPath?: string | null };
type Modal = "centros" | "plantillas" | "origen" | "periodo" | null;

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api${path}`, { credentials: "include", ...init });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || "No se pudo completar la operación.");
  return data as T;
}

const madridNow = () => {
  const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Madrid", year: "numeric", month: "2-digit" }).formatToParts();
  const read = (kind: string) => parts.find((part) => part.type === kind)?.value ?? "";
  return { anio: Number(read("year")), mes: read("month") };
};
const monthName = (month: string) => new Intl.DateTimeFormat("es-ES", { month: "long" }).format(new Date(2026, Number(month) - 1, 1));
const humanFileState = (value: string) => ({ encontrado_onedrive: "Encontrado en OneDrive", subido_manual: "Subido manualmente", faltante: "Faltante" }[value] ?? value.replaceAll("_", " "));
const humanSendState = (value: string) => ({ enviado: "Enviado", pendiente: "Pendiente", error_envio: "Error de envío" }[value] ?? value.replaceAll("_", " "));

function App() {
  const client = useQueryClient();
  const [screen, setScreen] = useState<"envio" | "historico">("envio");
  const [modal, setModal] = useState<Modal>(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [selectedLoteId, setSelectedLoteId] = useState<number | null>(null);
  const [notice, setNotice] = useState<string>("");
  const [sending, setSending] = useState(false);
  const [sendSuccess, setSendSuccess] = useState(false);
  const centros = useQuery({ queryKey: ["centros"], queryFn: () => api<{ data: Centro[] }>("/centros") });
  const templates = useQuery({ queryKey: ["templates"], queryFn: () => api<{ data: Template[] }>("/templates") });
  const lotes = useQuery({ queryKey: ["lotes"], queryFn: () => api<{ data: Lote[] }>("/lotes") });
  const connection = useQuery({ queryKey: ["microsoft"], queryFn: () => api<MicrosoftStatus>("/microsoft/status") });
  const detail = useQuery({ queryKey: ["lote", selectedLoteId], enabled: !!selectedLoteId, queryFn: () => api<Lote>(`/lotes/${selectedLoteId}`) });
  useEffect(() => { if (!selectedLoteId && lotes.data?.data[0]) setSelectedLoteId(lotes.data.data[0].id); }, [lotes.data, selectedLoteId]);
  useEffect(() => { const result = new URLSearchParams(location.search).get("microsoft"); if (result) { setNotice(result === "connected" ? "Microsoft conectado correctamente." : "No se pudo conectar Microsoft."); history.replaceState({}, "", location.pathname); void connection.refetch(); } }, [connection]);
  const refresh = () => void Promise.all(["centros", "templates", "lotes", "lote", "microsoft"].map((key) => client.invalidateQueries({ queryKey: [key] })));
  const selected = detail.data;
  const counters = useMemo(() => {
    const items = selected?.items ?? [];
    return { listos: items.filter((item) => item.archivoEstado !== "faltante").length, enviados: items.filter((item) => item.envioEstado === "enviado").length, faltan: items.filter((item) => item.archivoEstado === "faltante").length };
  }, [selected]);
  const send = useMutation({ mutationFn: () => api(`/lotes/${selectedLoteId}/send`, { method: "POST" }), onSuccess: () => { refresh(); setSendSuccess(true); window.setTimeout(() => { setSending(false); setSendSuccess(false); }, 1800); }, onError: (error) => { setSending(false); setNotice(error instanceof Error ? error.message : "Error de envío"); } });
  const search = useMutation({ mutationFn: () => api(`/lotes/${selectedLoteId}/search-onedrive`, { method: "POST" }), onSuccess: () => { setNotice("Archivos comprobados en OneDrive."); refresh(); }, onError: (error) => setNotice(error instanceof Error ? error.message : "Error al buscar") });
  const startSending = () => { setSending(true); send.mutate(); };
  const createLote = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const lote = await api<Lote>("/lotes", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ anio: Number(form.get("anio")), mesNumero: form.get("mesNumero"), extensionArchivo: form.get("extensionArchivo"), templateId: Number(form.get("templateId")) }) }); setSelectedLoteId(lote.id); setModal(null); setNotice("Período generado correctamente."); refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo generar el período"); } };
  const upload = async (itemId: number, file: File) => { try { await api(`/items/${itemId}/upload`, { method: "POST", headers: { "content-type": file.type || "application/octet-stream", "x-file-name": file.name }, body: file }); setNotice("Archivo subido correctamente."); refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo subir el archivo"); } };
  const navigate = (next: "envio" | "historico") => { setScreen(next); setMenuOpen(false); };

  return <div className="boom-app">
    <aside className={`sidebar ${menuOpen ? "is-open" : ""}`}>
      <div className="sidebar-brand"><img src="/boom-logo.png" alt="Muebles BOOM" /></div>
      <nav className="sidebar-nav"><button className={screen === "envio" ? "is-active" : ""} onClick={() => navigate("envio")}><Send size={20} />Envío de cifras</button></nav>
    </aside>
    {menuOpen && <button className="sidebar-backdrop" aria-label="Cerrar menú" onClick={() => setMenuOpen(false)} />}
    <main className="workspace">
      <header className="topbar"><button className="mobile-menu" aria-label="Abrir menú" onClick={() => setMenuOpen(true)}><Menu size={22} /></button><div className="topbar-spacer" /><button className="onedrive-status" onClick={() => setModal("origen")}><Cloud size={18} />{connection.data?.connected ? connection.data.accountEmail || "OneDrive conectado" : "Microsoft sin conectar"}</button></header>
      {notice && <div className="notice" role="status"><span>{notice}</span><button onClick={() => setNotice("")} aria-label="Cerrar"><X size={17} /></button></div>}
      {screen === "envio" ? <EnvioScreen selected={selected} selectedLoteId={selectedLoteId} lotes={lotes.data?.data ?? []} activeCenters={centros.data?.data.filter((centro) => centro.activo).length ?? 0} counters={counters} connected={!!connection.data?.connected} loading={detail.isLoading} searching={search.isPending} sending={sending} onSelect={setSelectedLoteId} onOpen={setModal} onHistory={() => navigate("historico")} onSearch={() => search.mutate()} onSend={startSending} onUpload={upload} /> : <HistoricoScreen lotes={lotes.data?.data ?? []} onBack={() => navigate("envio")} onOpen={(id) => { setSelectedLoteId(id); navigate("envio"); }} />}
    </main>
    {sending && <SendOverlay success={sendSuccess} />}
    {modal === "periodo" && <ModalShell title="Generar período" onClose={() => setModal(null)}><LoteForm templates={templates.data?.data ?? []} onSubmit={createLote} /></ModalShell>}
    {modal === "centros" && <ModalShell title="Centros" onClose={() => setModal(null)} wide><Centros data={centros.data?.data ?? []} done={refresh} message={setNotice} /></ModalShell>}
    {modal === "plantillas" && <ModalShell title="Plantillas" onClose={() => setModal(null)} wide><Plantillas data={templates.data?.data ?? []} done={refresh} message={setNotice} /></ModalShell>}
    {modal === "origen" && <ModalShell title="Origen de archivos" onClose={() => setModal(null)}><Conexion status={connection.data} done={refresh} message={setNotice} /></ModalShell>}
  </div>;
}

function EnvioScreen({ selected, selectedLoteId, lotes, activeCenters, counters, connected, loading, searching, sending, onSelect, onOpen, onHistory, onSearch, onSend, onUpload }: { selected?: Lote; selectedLoteId: number | null; lotes: Lote[]; activeCenters: number; counters: { listos: number; enviados: number; faltan: number }; connected: boolean; loading: boolean; searching: boolean; sending: boolean; onSelect: (id: number) => void; onOpen: (modal: Modal) => void; onHistory: () => void; onSearch: () => void; onSend: () => void; onUpload: (id: number, file: File) => void }) {
  return <section className="content-stack">
    <div className="page-heading"><div className="heading-title"><span className="heading-icon"><Send size={28} /></span><div><h1>Envío de cifras</h1><p>Declaraciones de ventas por centro. Envío masivo de emails.</p></div></div><div className="heading-actions"><button className="outline-button" onClick={onHistory}><History size={19} />Histórico</button><button className="outline-button" onClick={() => onOpen("origen")}><Cloud size={19} />Origen de archivos</button><button className="outline-button" onClick={() => onOpen("plantillas")}><FileSpreadsheet size={19} />Plantillas</button><button className="outline-button" onClick={() => onOpen("centros")}><Building2 size={19} />Centros</button><button className="outline-button" onClick={() => onOpen("periodo")}><Plus size={19} />Generar período</button></div></div>
    <section className="boom-card lote-card"><div className="period-row"><div><p className="field-label">Período seleccionado</p><div className="period-controls"><select aria-label="Período seleccionado" value={selectedLoteId ?? ""} onChange={(event) => onSelect(Number(event.target.value))}><option value="" disabled>Selecciona un período</option>{lotes.map((lote) => <option value={lote.id} key={lote.id}>{`${lote.anio}.${lote.mesNumero} - ${lote.mesNombre} ${lote.anio}`}</option>)}</select><button className="red-button" disabled={!selected || searching} onClick={onSearch}><RefreshCw size={17} className={searching ? "spin" : ""} />{searching ? "Buscando…" : "Buscar archivos"}</button><button className="red-button" disabled={!selected || sending} onClick={onSend}><Send size={17} />{sending ? "Enviando emails…" : "Enviar emails"}</button></div></div><span className={`lote-status ${selected?.estado === "enviado" ? "success" : selected?.estado === "error" ? "danger" : ""}`}>Estado del lote: {selected?.estado ?? "Sin lote"}</span></div>
      <div className="counters"><span>Total centros: {activeCenters}</span><span>Listos para enviar: {counters.listos}</span><span>Enviados: {counters.enviados}</span><span>Faltan archivos: {counters.faltan}</span><span>OneDrive: {connected ? "Conectado" : "Pendiente"}</span></div>
      <Items items={selected?.items ?? []} loading={loading} onUpload={onUpload} />
    </section>
  </section>;
}

function Items({ items, loading, onUpload }: { items: Item[]; loading: boolean; onUpload: (id: number, file: File) => void }) { return <div className="data-table-wrap"><table className="items-table"><thead><tr className="table-groups"><th colSpan={2} className="group-data">Datos</th><th colSpan={2} className="group-mail">Correo electrónico</th><th colSpan={2} className="group-subject">Asunto correo electrónico</th><th className="group-body">Texto correo electrónico</th><th colSpan={2} className="group-file">Ubicación PDF</th><th>Estado archivo</th><th>Estado envío</th></tr><tr className="table-columns"><th>Parque / Centro</th><th>Localidad</th><th>E-mail 01</th><th>E-mail 02</th><th>Año</th><th>Mes</th><th>Asunto carpeta</th><th>Nombre archivo</th><th>Origen archivo</th><th></th><th></th></tr></thead><tbody>{loading ? <tr><td colSpan={11} className="empty-state">Cargando lote…</td></tr> : items.length === 0 ? <tr><td colSpan={11} className="empty-state">Selecciona o genera un período para ver sus filas.</td></tr> : items.map((item) => <tr key={item.id}><td className="strong">{item.parqueCentroSnapshot}</td><td>{item.localidadSnapshot}</td><td className="email">{item.destinatarios[0] || "—"}</td><td className="email">{item.destinatarios[1] || "—"}</td><td>—</td><td>—</td><td className="truncate">{item.asunto}</td><td className="strong">{item.storageOriginalFileName || item.archivoNombre}</td><td className="path-cell">{item.oneDrivePathEsperado || "—"}<label className="upload-link"><FileUp size={14} />Subir<input type="file" accept=".pdf,.xlsx,.xls,.xlsm,.csv" onChange={(event) => event.target.files?.[0] && onUpload(item.id, event.target.files[0])} /></label></td><td><span className={`state-badge ${item.archivoEstado === "faltante" ? "bad" : "good"}`}>{humanFileState(item.archivoEstado)}</span>{item.error && <small className="row-error">{item.error}</small>}</td><td><span className={`state-badge ${item.envioEstado === "enviado" ? "good" : item.envioEstado === "error_envio" ? "bad" : "neutral"}`}>{humanSendState(item.envioEstado)}</span></td></tr>)}</tbody></table></div>; }

function ModalShell({ title, children, onClose, wide = false }: { title: string; children: React.ReactNode; onClose: () => void; wide?: boolean }) { return <div className="modal-backdrop" role="presentation"><section className={`modal-card ${wide ? "modal-wide" : ""}`} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Cerrar"><X size={21} /></button></header><div className="modal-content">{children}</div></section></div>; }

function LoteForm({ templates, onSubmit }: { templates: Template[]; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) { const now = madridNow(); return <form onSubmit={onSubmit} className="editor-form lote-form"><label>Año<input name="anio" type="number" min="2000" max="2100" defaultValue={now.anio} required /></label><label>Mes<select name="mesNumero" defaultValue={now.mes}>{Array.from({ length: 12 }, (_, index) => { const value = String(index + 1).padStart(2, "0"); return <option value={value} key={value}>{monthName(value)} ({value})</option>; })}</select></label><label>Extensión<input name="extensionArchivo" defaultValue="pdf" required /></label><label>Plantilla<select name="templateId" required>{templates.filter((template) => template.activo).map((template) => <option key={template.id} value={template.id}>{template.nombre}</option>)}</select></label><div className="form-actions"><button className="red-button" type="submit" disabled={!templates.some((template) => template.activo)}><Plus size={17} />Generar período</button></div>{!templates.some((template) => template.activo) && <p className="form-hint">Crea primero una plantilla activa.</p>}</form>; }

function Centros({ data, done, message }: { data: Centro[]; done: () => void; message: (value: string) => void }) { const [editing, setEditing] = useState<Partial<Centro> | null>(null); const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { ...Object.fromEntries(form), activo: form.get("activo") === "on" }; try { await api(editing?.id ? `/centros/${editing.id}` : "/centros", { method: editing?.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setEditing(null); done(); message("Centro guardado correctamente."); } catch (error) { message(error instanceof Error ? error.message : "Error al guardar el centro"); } }; return <div className="management"><div className="management-actions"><p>Destinatarios y carpeta relativa de cada centro.</p><button className="red-button" onClick={() => setEditing({ activo: true })}><Plus size={17} />Añadir centro</button></div>{editing && <form className="editor-form" onSubmit={save}><label>Parque / centro<input name="parqueCentro" defaultValue={editing.parqueCentro} required /></label><label>Localidad<input name="localidad" defaultValue={editing.localidad} required /></label><label>Email principal<input name="emailPrimario" type="email" defaultValue={editing.emailPrimario} required /></label><label>Email secundario<input name="emailSecundario" type="email" defaultValue={editing.emailSecundario ?? ""} /></label><label className="span-all">Carpeta dentro de la raíz OneDrive<input name="oneDriveFolderPath" defaultValue={editing.oneDriveFolderPath ?? ""} /></label><label className="check-label"><input name="activo" type="checkbox" defaultChecked={editing.activo ?? true} />Centro activo</label><div className="form-actions"><button className="red-button">Guardar</button><button type="button" className="outline-button small" onClick={() => setEditing(null)}>Cancelar</button></div></form>}<div className="simple-table-wrap"><table><thead><tr><th>Centro</th><th>Localidad</th><th>Correos</th><th>Carpeta OneDrive</th><th></th></tr></thead><tbody>{data.length === 0 ? <tr><td colSpan={5} className="empty-state">No hay centros configurados.</td></tr> : data.map((row) => <tr key={row.id}><td className="strong">{row.parqueCentro}</td><td>{row.localidad}</td><td className="email">{[row.emailPrimario, row.emailSecundario].filter(Boolean).join(", ")}</td><td>{row.oneDriveFolderPath || "—"}</td><td><button className="table-action" onClick={() => setEditing(row)}><Pencil size={15} />Editar</button></td></tr>)}</tbody></table></div></div>; }

function Plantillas({ data, done, message }: { data: Template[]; done: () => void; message: (value: string) => void }) { const [editing, setEditing] = useState<Partial<Template> | null>(null); const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { ...Object.fromEntries(form), activo: form.get("activo") === "on" }; try { await api(editing?.id ? `/templates/${editing.id}` : "/templates", { method: editing?.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); setEditing(null); done(); message("Plantilla guardada correctamente."); } catch (error) { message(error instanceof Error ? error.message : "Error al guardar la plantilla"); } }; return <div className="management"><div className="management-actions"><p>Variables: {"{{saludo}}, {{localidad}}, {{parque_centro}}, {{mes_nombre}}, {{anio}}"}</p><button className="red-button" onClick={() => setEditing({ activo: true })}><Plus size={17} />Añadir plantilla</button></div>{editing && <form className="editor-form" onSubmit={save}><label>Nombre<input name="nombre" defaultValue={editing.nombre} required /></label><label>Asunto<input name="asuntoTemplate" defaultValue={editing.asuntoTemplate} required /></label><label className="span-all">Cuerpo<textarea name="cuerpoTemplate" defaultValue={editing.cuerpoTemplate} required /></label><label>Saludo opcional<input name="saludoDefault" defaultValue={editing.saludoDefault ?? ""} /></label><label className="check-label"><input name="activo" type="checkbox" defaultChecked={editing.activo ?? true} />Plantilla activa</label><div className="form-actions"><button className="red-button">Guardar</button><button type="button" className="outline-button small" onClick={() => setEditing(null)}>Cancelar</button></div></form>}<div className="simple-table-wrap"><table><thead><tr><th>Nombre</th><th>Asunto</th><th>Vista previa</th><th></th></tr></thead><tbody>{data.length === 0 ? <tr><td colSpan={4} className="empty-state">No hay plantillas configuradas.</td></tr> : data.map((row) => <tr key={row.id}><td className="strong">{row.nombre}</td><td>{row.asuntoTemplate}</td><td className="preview-cell">{row.cuerpoTemplate}</td><td><button className="table-action" onClick={() => setEditing(row)}><Pencil size={15} />Editar</button></td></tr>)}</tbody></table></div></div>; }

function Conexion({ status, done, message }: { status?: MicrosoftStatus; done: () => void; message: (value: string) => void }) { const [root, setRoot] = useState(status?.rootPath ?? ""); useEffect(() => setRoot(status?.rootPath ?? ""), [status?.rootPath]); const saveRoot = async () => { try { await api("/microsoft/root", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ rootPath: root }) }); done(); message("Carpeta raíz actualizada correctamente."); } catch (error) { message(error instanceof Error ? error.message : "Error al guardar la carpeta"); } }; return <div className="connection-dialog"><span className="connection-icon"><Cloud size={27} /></span><h3>OneDrive</h3><p>Conecta tu cuenta Microsoft para leer los archivos de tu OneDrive. Los correos se envían temporalmente mediante el SMTP configurado.</p><p><b>Estado:</b> {status?.connected ? `Conectado como ${status.accountEmail}` : "Sin conectar"}</p>{status?.connected ? <><label className="root-label">Carpeta raíz OneDrive<input value={root} onChange={(event) => setRoot(event.target.value)} placeholder="/Cifras" /></label><button className="red-button" onClick={saveRoot}>Guardar carpeta</button><button className="outline-button small" onClick={() => { location.href = "/api/microsoft/connect" }}>Reconectar OneDrive</button></> : <button className="red-button" onClick={() => { location.href = "/api/microsoft/connect" }}><Cloud size={17} />Conectar OneDrive</button>}</div>; }

function HistoricoScreen({ lotes, onBack, onOpen }: { lotes: Lote[]; onBack: () => void; onOpen: (id: number) => void }) { return <section className="content-stack"><div className="page-heading"><div className="heading-title"><span className="heading-icon"><History size={28} /></span><div><h1>Histórico de envío de cifras</h1><p>Consulta los períodos generados y su estado de envío.</p></div></div><button className="outline-button" onClick={onBack}><ChevronLeft size={19} />Volver a envío de cifras</button></div><section className="boom-card"><div className="simple-table-wrap"><table><thead><tr><th>Período</th><th>Extensión</th><th>Estado</th><th></th></tr></thead><tbody>{lotes.length === 0 ? <tr><td colSpan={4} className="empty-state">No hay períodos en el histórico.</td></tr> : lotes.map((lote) => <tr key={lote.id}><td className="strong">{lote.mesNombre} {lote.anio}</td><td>.{lote.extensionArchivo}</td><td><span className={`state-badge ${lote.estado === "enviado" ? "good" : lote.estado === "error" ? "bad" : "neutral"}`}>{lote.estado}</span></td><td><button className="table-action" onClick={() => onOpen(lote.id)}>Abrir lote</button></td></tr>)}</tbody></table></div></section></section>; }

function SendOverlay({ success }: { success: boolean }) { return <div className="send-overlay" role="status"><div className="send-feedback">{success ? <><span className="success-orb"><CheckCircle2 size={68} /></span><h2>Emails enviados</h2><p>El envío del período ha finalizado correctamente.</p></> : <><span className="sending-logo"><img src="/boom-logo.png" alt="" /></span><h2>Enviando emails</h2><p>Estamos procesando el período seleccionado.</p></>}</div></div>; }

if ("serviceWorker" in navigator) window.addEventListener("load", () => void navigator.serviceWorker.register("/sw.js"));
createRoot(document.getElementById("root")!).render(<QueryClientProvider client={new QueryClient()}><App /></QueryClientProvider>);
