import { useEffect, useRef, useState } from "react";

type TemplateValue = { id?: number; nombre: string; asuntoTemplate: string; cuerpoTemplate: string; saludoDefault?: string; activo: boolean };
type Field = "asuntoTemplate" | "cuerpoTemplate";
const variables = [
  { key: "saludo", color: "violet" }, { key: "parque_centro", color: "blue" }, { key: "localidad", color: "green" }, { key: "mes_nombre", color: "orange" }, { key: "año", color: "pink" }
];
const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
function toEditorHtml(value: string) { return value.split(/(\{\{\s*(?:saludo|parque_centro|localidad|mes_nombre|año)\s*\}\})/gi).map((part) => { const match = part.match(/^\{\{\s*([^}]+?)\s*\}\}$/); if (match) { const item = variables.find((candidate) => candidate.key === match[1]); if (item) return `<span data-template-variable="${item.key}" contenteditable="false" class="template-chip ${item.color}">${item.key}</span>&nbsp;`; } return escapeHtml(part).replace(/\n/g, "<br>"); }).join(""); }
function serialize(element: HTMLElement) { const walk = (node: Node): string => { if (node.nodeType === Node.TEXT_NODE) return node.textContent || ""; if (node.nodeType !== Node.ELEMENT_NODE) return ""; const html = node as HTMLElement; const variable = html.dataset.templateVariable; if (variable) return `{{${variable}}}`; if (html.tagName === "BR") return "\n"; const content = Array.from(html.childNodes).map(walk).join(""); return ["DIV", "P"].includes(html.tagName) ? `${content}\n` : content; }; return Array.from(element.childNodes).map(walk).join("").replace(/\u00a0/g, " ").replace(/\n{3,}/g, "\n\n").trimEnd(); }
function selectionRange() { const selection = window.getSelection(); return selection?.rangeCount ? selection.getRangeAt(0).cloneRange() : null; }
function rangeAtPoint(x: number, y: number) { const documentWithCaret = document as Document & { caretRangeFromPoint?: (x: number, y: number) => Range | null; caretPositionFromPoint?: (x: number, y: number) => { offsetNode: Node; offset: number } | null }; if (documentWithCaret.caretRangeFromPoint) return documentWithCaret.caretRangeFromPoint(x, y); const position = documentWithCaret.caretPositionFromPoint?.(x, y); if (!position) return null; const range = document.createRange(); range.setStart(position.offsetNode, position.offset); range.collapse(true); return range; }
export function RichTemplateEditor({ value, close, save }: { value: TemplateValue; close(): void; save(value: TemplateValue): void }) {
  const [draft, setDraft] = useState(value); const editors = useRef<Record<Field, HTMLDivElement | null>>({ asuntoTemplate: null, cuerpoTemplate: null }); const lastRange = useRef<Range | null>(null); const active = useRef<Field>("cuerpoTemplate");
  useEffect(() => { setDraft(value); }, [value]);
  useEffect(() => { (Object.keys(editors.current) as Field[]).forEach((field) => { const element = editors.current[field]; if (element && document.activeElement !== element) element.innerHTML = toEditorHtml(draft[field]); }); }, [draft.asuntoTemplate, draft.cuerpoTemplate]);
  const remember = (field: Field) => { active.current = field; const range = selectionRange(); if (range && editors.current[field]?.contains(range.startContainer)) lastRange.current = range; };
  const sync = (field: Field) => { const element = editors.current[field]; if (element) setDraft((current) => ({ ...current, [field]: serialize(element) })); remember(field); };
  const insert = (key: string, field = active.current, range = lastRange.current) => { const editor = editors.current[field]; if (!editor) return; editor.focus(); const target = range && editor.contains(range.startContainer) ? range : (() => { const end = document.createRange(); end.selectNodeContents(editor); end.collapse(false); return end; })(); target.deleteContents(); const chip = document.createElement("span"); chip.dataset.templateVariable = key; chip.contentEditable = "false"; chip.className = `template-chip ${variables.find((item) => item.key === key)?.color || "violet"}`; chip.textContent = key; const spacer = document.createTextNode(" "); target.insertNode(spacer); target.insertNode(chip); const after = document.createRange(); after.setStartAfter(spacer); after.collapse(true); const selection = window.getSelection(); selection?.removeAllRanges(); selection?.addRange(after); lastRange.current = after.cloneRange(); sync(field); };
  const editor = (field: Field, label: string, placeholder: string) => <label>{label}<div className="rich-editor-shell"><div ref={(element) => { editors.current[field] = element; }} contentEditable suppressContentEditableWarning className={`rich-editor ${field === "cuerpoTemplate" ? "body-editor" : ""}`} data-placeholder={placeholder} onFocus={() => remember(field)} onClick={() => remember(field)} onKeyUp={() => remember(field)} onInput={() => sync(field)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); const key = event.dataTransfer.getData("text/template-variable"); if (key) insert(key, field, rangeAtPoint(event.clientX, event.clientY)); }} /></div></label>;
  return <div className="nested-backdrop"><section className="template-editor"><button className="close" onClick={close}>×</button><h3>{value.id ? "Editar plantilla" : "Nueva plantilla"}</h3><p>Configura asunto y cuerpo del correo con variables del lote.</p><div className="template-top"><label>Nombre<input autoFocus value={draft.nombre} onChange={(event) => setDraft({ ...draft, nombre: event.target.value })}/></label><label className="active-control">Plantilla activa <button className={`switch ${draft.activo ? "on" : ""}`} onClick={() => setDraft({ ...draft, activo: !draft.activo })}><span/></button></label></div>{editor("asuntoTemplate", "Asunto", "Escribe el asunto y arrastra variables aquí...")}{editor("cuerpoTemplate", "Cuerpo", "Escribe el cuerpo y arrastra variables aquí...")}<label>Saludo por defecto opcional<input value={draft.saludoDefault} onChange={(event) => setDraft({ ...draft, saludoDefault: event.target.value })} placeholder="Vacío = Buenos días / Buenas tardes automático"/></label><div className="variables"><strong>Variables disponibles</strong><p>Arrastra una etiqueta o haz doble clic para insertarla donde estás escribiendo.</p><div>{variables.map((item) => <button key={item.key} className={`palette-chip ${item.color}`} draggable onDragStart={(event) => { event.dataTransfer.setData("text/template-variable", item.key); event.dataTransfer.effectAllowed = "copy"; }} onMouseDown={(event) => event.preventDefault()} onDoubleClick={() => insert(item.key)}>{item.key}</button>)}</div></div><footer><button className="outline" onClick={close}>Cancelar</button><button className="purple" onClick={() => save(draft)}>Guardar plantilla</button></footer></section></div>;
}
